const playerStats = {
    'GouenjiS': {
        ID: 'GouenjiS',
        Name: 'Axel Blaze',
        Undub_Name: 'Shuuya Gouenji',
        FP: 160,
        TP: 156,
        Strength: 68,
        Dribble: 79,
        Shoot: 76,
        Speed: 75,
        Keeper: 50,
        Hissatsu: ['SDash', 'Fire Tornado', 'Inazuma Drop'],
        FaceSprite: 'Gouenji_face',
        H_Voice: ''
    },
    'KazemaruI': {
        ID: 'KazemaruI',
        Name: 'Nathan Swift',
        Undub_Name: 'Ichirouta Kazemaru',
        FP: 150,
        TP: 170,
        Strength: 62,
        Dribble: 81,
        Shoot: 59,
        Speed: 75,
        Keeper: 50,
        Hissatsu: ['SDash', 'Clone Defense'],
        FaceSprite: 'Kazemaru_face',
        H_Voice: ''
    },
    'KabeyamaH': {
        ID: 'KabeyamaH',
        Name: 'Jack Wallside',
        Undub_Name: 'Heigoro Kabeyama',
        FP: 180,
        TP: 130,
        Strength: 82,
        Dribble: 54,
        Shoot: 56,
        Speed: 60,
        Keeper: 68,
        Hissatsu: ['SDash', 'The Wall', 'Rock Wall Dam'],
        FaceSprite: 'kabeyama_face',
        H_Voice: ''
    },
    'KidouY': {
        ID: 'KidouY',
        Name: 'Jude Sharp',
        Undub_Name: 'Yuuto Kidou',
        FP: 165,
        TP: 190,
        Strength: 70,
        Dribble: 85,
        Shoot: 72,
        Speed: 73,
        Keeper: 55,
        Hissatsu: ['SDash', 'Illusion Ball', 'Emperor Penguin'],
        FaceSprite: 'kidou_face',
        H_Voice: ''
    },
    'EndoM': {
        ID: 'EndoM',
        Name: 'Mark Evans',
        Undub_Name: 'Mamoru Endou',
        FP: 170,
        TP: 180,
        Strength: 71,
        Dribble: 65,
        Shoot: 60,
        Speed: 75,
        Keeper: 88,
        Hissatsu: ['SDash', 'God Hand', 'Majin The Hand'],
        FaceSprite: 'endo_face',
        H_Voice: ''
    },
    'Gran': {
        ID: 'Gran',
        Name: 'Xene',
        Undub_Name: 'Gran',
        FP: 175,
        TP: 185,
        Strength: 75,
        Dribble: 80,
        Shoot: 78,
        Speed: 82,
        Keeper: 60,
        Hissatsu: ['SDash', 'Ryuusei Blade', 'Supernova'],
        FaceSprite: 'Xene_face',
        H_Voice: ''
    },
    'Aphrodi': {
        ID: 'Aphrodi',
        Name: 'Aphrodite',
        Undub_Name: 'Aphrodi',
        FP: 160,
        TP: 175,
        Strength: 65,
        Dribble: 83,
        Shoot: 77,
        Speed: 78,
        Keeper: 55,
        Hissatsu: ['SDash', 'Heaven\'s Time', 'God Knows'],
        FaceSprite: 'Afuro_face',
        H_Voice: ''
    },
    'SakumaJ': {
        ID: 'SakumaJ',
        Name: 'David Samford',
        Undub_Name: 'Jirou Sakuma',
        FP: 155,
        TP: 165,
        Strength: 68,
        Dribble: 75,
        Shoot: 74,
        Speed: 72,
        Keeper: 52,
        Hissatsu: ['SDash', 'Koutei Penguin 2gou', 'Tsunami Wall'],
        FaceSprite: 'sakuma_face',
        H_Voice: ''
    },
    'FubukiS': {
        ID: 'FubukiS',
        Name: 'Shawn Froste',
        Undub_Name: 'Shirou Fubuki',
        FP: 165,
        TP: 180,
        Strength: 70,
        Dribble: 80,
        Shoot: 79,
        Speed: 74,
        Keeper: 65,
        Hissatsu: ['SDash', 'Eternal Blizzard', 'Wolf Legend'],
        FaceSprite: 'Shirou_face',
        H_Voice: ''
    },
    'GendaK': {
        ID: 'GendaK',
        Name: 'Joseph King',
        Undub_Name: 'Koujirou Genda',
        FP: 180,
        TP: 170,
        Strength: 75,
        Dribble: 60,
        Shoot: 65,
        Speed: 70,
        Keeper: 85,
        Hissatsu: ['SDash', 'Beast Fang', 'Million Hands'],
        FaceSprite: 'Genda_face',
        H_Voice: ''
    }
};
